### ISSUE TITLE
PM2.5 reading is constantly 1000?

### ISSUE THREAD

**Issue by buddyrich33** [fjs21/homebridge-blueair#11]
Just got a Classic 280i and installed this plugin.

Not sure if its related to issue #7 but my PM2.5 reading is constantly 1000...  Not sure if that is accurate or not but the app has it as 0 and is excellent AQ (blue)... as far as I know 1000 ug/m2 is crazy high for PM2.5.  On the other hand PM10 density matches the app at 0.

**Comment by fjs21** [comment]
I'm seeing the same issue here as well. I'll take a look and see if I can diagnose the issue.

**Comment by fjs21** [comment]
Should be fixed in v1.0.8
