### ISSUE TITLE
This plugin generated a warning from the characteristic 'PM10 Density'

### ISSUE THREAD

**Issue by sasojadrovski** [fjs21/homebridge-blueair#3]
Hi @fjs21,

Thank you so much for updating this plugin and fixing some of the issues. 

I just installed it yesterday, and the logs keep reporting the following warning (every 5 seconds):
>This plugin generated a warning from the characteristic 'PM10 Density': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

I was unable to find a way to disable that characteristic in the plugin's settings, so I am reaching out to let you know about this. I hope it's something you might be able to look into.

Thanks!

**Comment by fjs21** [comment]
This should be fixed in v0.6.12. Instead you should see something in the homebridge log to let you know it was unable to find the PM10 density. Let me know if you come across other bugs.

**Comment by sasojadrovski** [comment]
Hi @fjs21,

Thank you for looking into this so promptly. You are correct, now I see different types of logs, but I was thinking that logging the same warning every 5 seconds might be a bit too much and it pollutes the logs. 

Maybe it should log it only once and then stop? What do you think?

Looking forward to hearing from you.

**Comment by fjs21** [comment]
Oh. Sure, I can just move it to debug rather than info.
