### ISSUE TITLE
Add Support for Model: 411i MAX

### ISSUE THREAD

**Issue by jonato1** [fjs21/homebridge-blueair#330]
Starting a new issue to track all of the work related to adding support for 411i MAX. 

Requested features: auto mode, dynamic fan speed, child lock, LED, and PM 2.5 sensors, temp, humidity.

Pull Request #285 from @rmcardle, reviewed by @tmysl. Watchers: @cmfrazier, @bdroths, @jdsebo15, @mzruya

**Comment by jonato1** [comment]
Pull request #285 adds support for everything listed above, except for temp and humidity. Pending additional commit.

**Comment by jonato1** [comment]
Done - This will be released with v1.3.0 shortly.

**Comment by rmcardle** [comment]
I don't think the 411i MAX supports temperature and humidity. The Blueair app doesn't show them and Homebridge with plugin 1.3.0 is just showing 0°C and 0%.

**Comment by jdsebo15** [comment]
My 411i max does not appear to have any sensors except PM2.5. Let me know if there is any other product information you guys need. We really appreciate y’all’s support.Best,Jarrett SeboOn Jul 9, 2023, at 10:25, Riley McArdle ***@***.***> wrote:﻿
I don't think the 411i MAX supports temperature and humidity. The Blueair app doesn't show them and Homebridge with plugin 1.3.0 is just showing 0°C and 0%.

**Comment by jonato1** [comment]
Hey @rmcardle and @rmcardle - Thanks for the heads up. I thought I saw from someone that the 411i Max has temp and humidity, but I may have misread in going through all of the comments. I'll make a commit to have it removed in the next release.

**Comment by jonato1** [comment]
v1.3.1 is released! Let me know if y'all see any additional concerns or issues. Also, if everything is working, that'd be great to know too!

**Comment by rmcardle** [comment]
1.3.1 is working great for me. I'm not sure how it got fixed because I don't see anything in the patches, but it's showing the air quality as "Excellent" now. Before it was just showing "Unknown". Maybe something in one of the dependencies that changed in f05157e666624499786c2ba194528116504253f8 fixed it?
