### ISSUE TITLE
Is the development of this plugin abandoned?

### ISSUE THREAD

**Issue by lensherm** [fjs21/homebridge-blueair#5]
Just curious if there will be further updates to this plugin.

**Comment by fjs21** [comment]
Yeah. Just been super busy over the holidays.
________________________________
From: lensherm ***@***.***>
Sent: Wednesday, December 29, 2021 6:28:38 AM
To: fjs21/homebridge-blueair ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fjs21/homebridge-blueair] Is the development of this plugin abandoned? (Issue #5)


Just curious if there will be further updates to this plugin.

**Comment by lensherm** [comment]
Got it. Thanks for your work on this.
