### ISSUE TITLE
Missing/wrong readings?

### ISSUE THREAD

**Issue by buczo23** [fjs21/homebridge-blueair#7]
Hi there, as per subject:
 This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic was supplied illegal value: number 1509.086 exceeded maximum of 1000. See https://git.io/JtMGR for more info.

My Blueair model is Classic 280i, how I can help in solving this issue? :)

**Comment by fjs21** [comment]
I can hide the error if needed. It seems that HomeKit cannot handle values greater than 1000, and I can just have it set anything reported as >1000 as 1000. However, before I do that, could you check in the BlueAir app that the value for PM2.5 is indeed accurate.

**Comment by fjs21** [comment]
Fixed in v0.8.11

**Comment by buczo23** [comment]
@fjs21 definitely there was something in it, as app showed proper levels, but the device by themself had orange light around PM2.5 indicator. After classic turn off/on everything seems working correctly.
