### ISSUE TITLE
VOC measurement in Home app is probably wrong

### ISSUE THREAD

**Issue by w194** [fjs21/homebridge-blueair#95]
Hello there,
I compared with an *Eve Room* HomeKit device and the value displayed from the BlueAir 680i is around 10 times higher.

Eve Room: 59 µg/m³
BlueAir 680i: 589 µg/m³

**Comment by fjs21** [comment]
I'll check at my end. Just to confirm. So the second value (589) comes from the BlueAir app and the Eve and Home app value is 10x less?

**Comment by jonato1** [comment]
@w194 Is this still an issue? If so, can you please provide a bit more insight, per Fraser's question above? If not, we will close this issue.

**Comment by jonato1** [comment]
Closing stale issue. Please re-open or open a new issue if the issue is persisting.
